// src/themes.js
export const themes = {
    light: {
      backgroundColor: "#f8f9fa",
      textColor: "#000000",
      cardColor: "#ffffff",
      borderColor: "#cccccc",
      inputBackgroundColor: "#ffffff",
      inputTextColor: "#000000",
      buttonColor: "#007bff",
    },
    dark: {
      backgroundColor: "#333333",
      textColor: "#ffffff",
      cardColor: "#444444",
      borderColor: "#666666",
      inputBackgroundColor: "#555555",
      inputTextColor: "#ffffff",
      buttonColor: "#007bff",
    },
    solarizedLight: {
      backgroundColor: "#fdf6e3",
      textColor: "#002b36",
      cardColor: "#eee8d5",
      borderColor: "#cb4b16",
      inputBackgroundColor: "#fdf6e3",
      inputTextColor: "#002b36",
      buttonColor: "#268bd2",
    },
    solarizedDark: {
      backgroundColor: "#002b36",
      textColor: "#fdf6e3",
      cardColor: "#073642",
      borderColor: "#859900",
      inputBackgroundColor: "#002b36",
      inputTextColor: "#fdf6e3",
      buttonColor: "#268bd2",
    },
    monokai: {
      backgroundColor: "#272822",
      textColor: "#f8f8f2",
      cardColor: "#3e3d32",
      borderColor: "#75715e",
      inputBackgroundColor: "#272822",
      inputTextColor: "#f8f8f2",
      buttonColor: "#ae81ff",
    },
    pastel: {
      backgroundColor: "#f3f8ff",
      textColor: "#333333",
      cardColor: "#ffffff",
      borderColor: "#a5d8ff",
      inputBackgroundColor: "#f3f8ff",
      inputTextColor: "#333333",
      buttonColor: "#7ac1ff",
    },
    highContrast: {
      backgroundColor: "#000000",
      textColor: "#ffffff",
      cardColor: "#121212",
      borderColor: "#ffffff",
      inputBackgroundColor: "#000000",
      inputTextColor: "#ffffff",
      buttonColor: "#00ffff",
    },
    earthTones: {
      backgroundColor: "#e1d8b9",
      textColor: "#3a2e1e",
      cardColor: "#d9cbb1",
      borderColor: "#6b5d43",
      inputBackgroundColor: "#e1d8b9",
      inputTextColor: "#3a2e1e",
      buttonColor: "#8b7d6b",
    },
    ocean: {
      backgroundColor: "#e6f7ff",
      textColor: "#006994",
      cardColor: "#b3e5fc",
      borderColor: "#009688",
      inputBackgroundColor: "#e6f7ff",
      inputTextColor: "#006994",
      buttonColor: "#00bcd4",
    },
    forest: {
      backgroundColor: "#e8f5e9",
      textColor: "#1b5e20",
      cardColor: "#c8e6c9",
      borderColor: "#388e3c",
      inputBackgroundColor: "#e8f5e9",
      inputTextColor: "#1b5e20",
      buttonColor: "#4caf50",
    },
    sunset: {
      backgroundColor: "#fff3e0",
      textColor: "#e65100",
      cardColor: "#ffe0b2",
      borderColor: "#ff7043",
      inputBackgroundColor: "#fff3e0",
      inputTextColor: "#e65100",
      buttonColor: "#ff5722",
    },
    lavender: {
      backgroundColor: "#f3e5f5",
      textColor: "#4a148c",
      cardColor: "#e1bee7",
      borderColor: "#7c4dff",
      inputBackgroundColor: "#f3e5f5",
      inputTextColor: "#4a148c",
      buttonColor: "#9575cd",
    },
    vintage: {
      backgroundColor: "#f5f5f0",
      textColor: "#3a2c1a",
      cardColor: "#e5d4c0",
      borderColor: "#5d4037",
      inputBackgroundColor: "#f5f5f0",
      inputTextColor: "#3a2c1a",
      buttonColor: "#8d6e63",
    },
    candy: {
      backgroundColor: "#ffebee",
      textColor: "#c2185b",
      cardColor: "#ffcdd2",
      borderColor: "#ff5252",
      inputBackgroundColor: "#ffebee",
      inputTextColor: "#c2185b",
      buttonColor: "#ff4081",
    },
    cyberpunk: {
      backgroundColor: "#0a0e23",
      textColor: "#ff00ff",
      cardColor: "#1a1033",
      borderColor: "#00ffff",
      inputBackgroundColor: "#0a0e23",
      inputTextColor: "#ff00ff",
      buttonColor: "#00ffaa",
    },
    autumn: {
      backgroundColor: "#fff8e1",
      textColor: "#bf360c",
      cardColor: "#ffcc80",
      borderColor: "#ff8f00",
      inputBackgroundColor: "#fff8e1",
      inputTextColor: "#bf360c",
      buttonColor: "#ff6f00",
    },
  };
  